services:
  - type: web
    name: ristak-app
    env: node
    region: oregon
    buildCommand: |
      npm install --prefix backend &&
      rm -rf frontend/node_modules frontend/.vite &&
      npm cache clean --force &&
      npm install --include=dev --prefix frontend &&
      echo "VITE_API_URL=https://$RENDER_EXTERNAL_HOSTNAME" > frontend/.env.production &&
      NODE_ENV=production npm run build --prefix frontend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ristak-db
          property: connectionString

databases:
  - name: ristak-db
    databaseName: ristak_db
    user: ristak_user
    plan: basic-256mb
    diskSizeGB: 15
